// Define the dictionary
var dictionary = {
    "hello": "olá",
    "goodbye": "adeus",
    "please": "por favor",
    "thank you": "obrigado/a",
    "yes": "sim",
    "no": "não",
    "sorry": "desculpe",
    "love": "amor",
    "one": "um",
    "two": "dois",
    "three": "três",
    "four": "quatro",
    "five": "cinco",
    "six": "seis",
    "seven": "sete",
    "eight": "oito",
    "nine": "nove",
    "ten": "dez",
    "eleven": "onze",
    "twelve": "doze",
    "thirteen": "treze",
    "fourteen": "quatorze",
    "fifteen": "quinze",
    "sixteen": "dezesseis",
    "seventeen": "dezessete",
    "eighteen": "dezoito",
    "nineteen": "dezenove",
    "twenty": "vinte",
    "thirty": "trinta",
    "forty": "quarenta",
    "fifty": "cinquenta",
    "sixty": "sessenta",
    "seventy": "setenta",
    "eighty": "oitenta",
    "ninety": "noventa",
    "hundred": "cem",
    "thousand": "mil",
    "million": "milhão",
    "billion": "bilhão",
    "trillion": "trilhão",
    "zero": "zero",
    "and": "e",
    "or": "ou",
    "not": "não",
    "yes": "sim",
    "no": "não",
    "please": "por favor",
    "thank you": "obrigado/a",
    "you're welcome": "de nada",
    "excuse me": "com licença",
    "sorry": "desculpe",
    "hello": "olá",
    "hi": "oi",
    "goodbye": "adeus",
    "see you later": "até mais tarde",
    "good morning": "bom dia",
    "good afternoon": "boa tarde",
    "good evening": "boa noite",
    "night": "noite",
    "day": "dia",
    "week": "semana",
    "month": "mês",
    "year": "ano",
    "today": "hoje",
    "yesterday": "ontem",
    "tomorrow": "amanhã",
    "now": "agora",
    "later": "depois",
    "before": "antes",
    "after": "depois",
    "soon": "em breve",
    "never": "nunca",
    "always": "sempre",
    "maybe": "talvez",
    "why": "por que",
    "what": "o que",
    "where": "onde",
    "when": "quando",
    "who": "quem",
    "how": "como",
    "which": "qual",
    "this": "este/a",
    "that": "aquele/a",
    "here": "aqui",
    "there": "lá",
    "good": "bom/a",
    "bad": "ruim",
    "happy": "feliz",
    "sad": "triste",
    "angry": "com raiva",
    "tired": "cansado/a",
    "hungry": "com fome",
    "thirsty": "com sede",
    "hot": "quente",
    "cold": "frio",
    "big": "grande",
    "small": "pequeno/a",
    "old": "velho/a",
    "new": "novo/a",
    "fast": "rápido/a",
    "slow": "devagar",
    "easy": "fácil",
    "difficult": "difícil",
    "beautiful": "bonito/a",
    "ugly": "feio/a",
    "a": "um",
    "able": "capaz",
    "about": "sobre",
    "above": "acima",
    "accept": "aceitar",
    "account": "conta",
    "across": "atravessar",
    "act": "ato",
    "add": "adicionar",
    "address": "endereço",
    "administration": "administração",
    "adult": "adulto",
    "advice": "conselho",
    "after": "depois",
    "again": "novamente",
    "against": "contra",
    "age": "idade",
    "agency": "agência",
    "agent": "agente",
    "ago": "atrás",
    "agree": "concordar",
    "air": "ar",
    "all": "todos",
    "allow": "permitir",
    "almost": "quase",
    "alone": "sozinho",
    "along": "ao longo",
    "already": "já",
    "also": "também",
    "although": "embora",
    "always": "sempre",
    "American": "americano",
    "among": "entre",
    "amount": "quantidade",
    "analysis": "análise",
    "and": "e",
    "animal": "animal",
    "another": "outro",
    "answer": "resposta",
    "any": "qualquer",
    "anyone": "qualquer um",
    "anything": "qualquer coisa",
    "appear": "aparecer",
    "apply": "aplicar",
    "approach": "abordagem",
    "area": "área",
    "argue": "argumentar",
    "arm": "braço",
    "around": "em volta",
    "arrive": "chegar",
    "art": "arte",
    "article": "artigo",
    "artist": "artista",
    "as": "como",
    "ask": "perguntar",
    "assume": "assumir",
    "at": "em",
    "attack": "ataque",
    "attention": "atenção",
    "attorney": "advogado",
    "audience": "público",
    "author": "autor",
    "authority": "autoridade",
    "available": "disponível",
    "avoid": "evitar",
    "away": "longe",
    "baby": "bebê",
    "back": "de volta",
    "bad": "ruim",
    "bag": "saco",
    "ball": "bola",
    "bank": "banco",
    "bar": "bar",
    "base": "base",
    "be": "ser",
    "beat": "bater",
    "beautiful": "bonito",
    "because": "porque",
    "become": "tornar-se",
    "bed": "cama",
    "before": "antes",
    "begin": "começar",
    "behavior": "comportamento",
    "behind": "atrás",
    "believe": "acreditar",
    "benefit": "benefício",
    "best": "melhor",
    "better": "melhor",
    "between": "entre",
    "beyond": "além",
    "apple": "maçã",
    "ant": "formiga",
    "airplane": "avião",
    "art": "arte",
    "apartment": "apartamento",
    "animal": "animal",
    "alphabet": "alfabeto",
    "adventure": "aventura",
    "amazing": "incrível",
    "amusement": "diversão",
    "banana": "banana",
    "bird": "pássaro",
    "bicycle": "bicicleta",
    "beach": "praia",
    "building": "edifício",
    "bus": "ônibus",
    "book": "livro",
    "blue": "azul",
    "butterfly": "borboleta",
    "business": "negócio",
    "car": "carro",
    "cat": "gato",
    "coffee": "café",
    "computer": "computador",
    "camera": "câmera",
    "city": "cidade",
    "cookie": "biscoito",
    "dog": "cachorro",
    "day": "dia",
    "dance": "dança",
    "dolphin": " golfinho",
    "doll": "boneca",
    "dream": "sonho",
    "dinner": "jantar",
    "ear": "orelha",
    "egg": "ovo",
    "elephant": "elefante",
    "energy": "energia",
    "enjoy": "curtir",
    "education": "educação",
    "evening": "noite",
    "fish": "peixe",
    "flower": "flor",
    "food": "comida",
    "forest": "floresta",
    "friend": "amigo",
    "football": "futebol",
    "family": "família",
    "fruit": "fruta",
    "game": "jogo",
    "guitar": "violão",
    "grass": "grama",
    "gift": "presente",
    "glasses": "óculos",
    "green": "verde",
    "horse": "cavalo",
    "hamburger": "hambúrguer",
    "hat": "chapéu",
    "home": "casa",
    "heart": "coração",
    "happy": "feliz",
    "ice cream": "sorvete",
    "island": "ilha",
    "idea": "ideia",
    "jazz": "jazz",
    "jeans": "jeans",
    "jam": "geleia",
    "journey": "jornada",
    "jungle": "selva",
    "jump": "pular",
    "key": "chave",
    "kite": "pipa",
    "kangaroo": "canguru",
    "kindness": "gentileza",
    "king": "rei",
    "knowledge": "conhecimento",
    "lamp": "lâmpada",
    "lake": "lago",
    "leaf": "folha",
    "love": "amor",
    "lunch": "almoço",
    "lion": "leão",
    "language": "linguagem",
    "library": "biblioteca",
    "moon": "luna",
    "mop": "esfregão",
    "music": "música",
    "nail": "unha",
    "name": "nome",
    "napkin": "guardanapo",
    "neck": "pescoço",
    "needle": "agulha",
    "nest": "ninho",
    "net": "rede",
    "news": "notícias",
    "ocean": "oceano",
    "office": "escritório",
    "oil": "óleo",
    "orange": "laranja",
    "oven": "forno",
    "owl": "coruja",
    "page": "página",
    "paint": "pintar",
    "pan": "panela",
    "pants": "calças",
    "paper": "papel",
    "party": "festa",
    "peach": "pêssego",
    "pear": "pêra",
    "pen": "caneta",
    "pencil": "lápis",
    "person": "pessoa",
    "phone": "telefone",
    "photo": "foto",
    "piano": "piano",
    "picture": "imagem",
    "pie": "torta",
    "pig": "porco",
    "pillow": "travesseiro",
    "pizza": "pizza",
    "plane": "avião",
    "plant": "planta",
    "plate": "prato",
    "play": "jogar",
    "please": "por favor",
    "pocket": "bolso",
    "pot": "panela",
    "potato": "batata",
    "price": "preço",
    "printer": "impressora",
    "pumpkin": "abóbora",
    "purse": "bolsa",
    "queen": "rainha",
    "question": "pergunta",
    "quiet": "quieto",
    "rabbit": "coelho",
    "radio": "rádio",
    "rain": "chuva",
    "rainbow": "arco-íris",
    "rat": "rato",
    "read": "ler",
    "red": "vermelho",
    "restaurant": "restaurante",
    "rice": "arroz",
    "ring": "anel",
    "river": "rio",
    "road": "estrada",
    "rock": "rocha",
    "room": "quarto",
    "rose": "rosa",
    "rug": "tapete",
    "run": "correr",
    "sad": "triste",
    "safe": "seguro",
    "sail": "navegar",
    "sand": "areia",
    "school": "escola",
    "scissors": "tesoura",
    "sea": "mar",
    "seat": "assento",
    "second": "segundo",
    "see": "ver",
    "shirt": "camisa",
    "shoe": "sapato",
    "shop": "loja",
    "shorts": "bermuda",
    "shoulder": "ombro",
    "shower": "ducha",
    "sick": "doente",
    "sign": "sinal",
    "silver": "prata",
    "sing": "cantar",
    "sink": "pia",
    "sink": "pias",
    "sip": "beber em pequenas quantidades",
    "sister": "irmã",
    "sit": "sentar",
    "six": "seis",
    "size": "tamanho",
    "skate": "andar de skate",
    "ski": "esquiar",
    "skin": "pele",
    "skirt": "saia",
    "sky": "céu",
    "sleep": "dormir",
    "slice": "fatia",
    "slip": "escorregar",
    "slow": "devagar",
    "small": "pequeno",
    "smart": "inteligente",
    "smell": "cheirar",
    "smile": "sorrir",
    "smoke": "fumar",
    "snack": "lanche",
    "snake": "cobra",
    "sneeze": "espirrar",
    "snow": "neve",
    "soap": "sabão",
    "sock": "meia",
    "soft": "macio",
    "software": "software",
    "soil": "solo",
    "soldier": "soldado",
    "solve": "resolver",
    "son": "filho",
    "song": "canção",
    "soon": "em breve",
    "sorry": "desculpa",
    "sound": "som",
    "soup": "sopa",
    "south": "sul",
    "space": "espaço",
    "speak": "falar",
    "special": "especial",
    "speed": "velocidade",
    "spell": "soletrar",
    "spend": "gastar",
    "spider": "aranha",
    "spoon": "colher",
    "sport": "esporte",
    "spot": "ponto",
    "spring": "primavera",
    "square": "quadrado",
    "stamp": "selo",
    "stand": "ficar em pé",
    "star": "estrela",
    "start": "começar",
    "state": "estado",
    "station": "estação",
    "stay": "ficar",
    "steal": "roubar",
    "step": "passo",
    "stick": "colar",
    "still": "ainda",
    "stomach": "estômago",
    "stone": "pedra",
    "stop": "parar",
    "store": "loja",
    "storm": "tempestade",
    "story": "história",
    "stove": "fogão",
    "strange": "estranho",
    "street": "rua",
    "strong": "forte",
    "student": "estudante",
    "study": "estudar",
    "stupid": "estúpido",
    "submarine": "submarino",
    "succeed": "ter sucesso",
    "such": "tal",
    "sudden": "repentino",
    "sugar": "açúcar",
    "summer": "verão",
    "sun": "sol",
    "supper": "jantar",
    "supply": "fornecer",
    "support": "suporte",
    "sure": "certo",
    "surface": "superficie",
    "surrender": "rendição",
    "swim": "nadar",
    "sweater": "suéter",
    "sweet": "doce",
    "swimwear": "roupa de banho",
    "sword": "espada",
    "system": "sistema",
    "syrup": "xarope",
    "symphony": "sinfonia",
    "sail": "vela",
    "salt": "sal",
    "sample": "amostra",
    "sand": "areia",
    "satellite": "satélite",
    "school": "escola",
    "science": "ciência",
    "scissors": "tesoura",
    "search": "pesquisa",
    "season": "estação",
    "secret": "segredo",
    "seed": "semente",
    "seek": "procurar",
    "seize": "apreender",
    "select": "selecionar",
    "selfish": "egoísta",
    "sentence": "frase",
    "separate": "separado",
    "serve": "servir",
    "session": "sessão",
    "settle": "resolver",
    "several": "vários",
    "severe": "grave",
    "shade": "sombra",
    "shadow": "sombras",
    "shame": "vergonha",
    "shape": "forma",
    "share": "compartilhar",
    "sharp": "afiado",
    "shelter": "abrigo",
    "shift": "mudança",
    "shine": "brilhar",
    "ship": "navio",
    "shirt": "camisa",
    "shock": "choque",
    "shoe": "sapato",
    "shoot": "atirar",
    "shop": "loja",
    "short": "curto",
    "shoulder": "ombro",
    "shout": "gritar",
    "show": "mostrar",
    "shrink": "encolher",
    "sick": "doente",
    "side": "lado",
    "sight": "visão",
    "sign": "sinal",
    "signal": "sinal",
    "silence": "silêncio",
    "silver": "prata",
    "similar": "semelhante",
    "simple": "simples",
    "since": "desde",
    "sing": "cantar",
    "single": "único",
    "sink": "afundar",
    "sister": "irmã",
    "situation": "situação",
    "size": "tamanho",
    "sketch": "esboço",
    "skill": "habilidade",
    "skin": "pele",
    "sky": "céu",
    "slave": "escravo",
    "sleep": "dormir",
    "slice": "fatia",
    "slide": "deslizar",
    "slight": "ligeiro",
    "slip": "escorregar",
    "slow": "devagar",
    "small": "pequeno",
    "smart": "inteligente",
    "smile": "sorriso",
    "smoke": "fumaça",
    "smooth": "suave",
    "snake": "cobra",
    "snow": "neve",
    "soak": "embeber",
    "soap": "sabão",
    "social": "social",
    "society": "sociedade",
    "soft": "macio",
    "software": "software",
    "soil": "solo",
    "soldier": "soldado",
    "solid": "sólido",
    "sorrow": "tristeza",
    "satisfy": "satisfazer",
    "shelter": "abrigo",
    "serious": "grave",
    "signature": "assinatura",
    "simple": "simples",
    "smile": "sorriso",
    "spend": "gastar",
    "support": "apoio",
    "table": "mesa",
    "tall": "alto",
    "taste": "gosto",
    "teach": "ensinar",
    "thirsty": "sede",
    "throw": "jogar",
    "tired": "cansado",
    "together": "juntos",
    "tomorrow": "amanhã",
    "travel": "viagem",
};

// Function to translate English to Nova
function translateEnglishToNova() {
    // Get the input text from the HTML element
    var inputText = document.getElementById("english").value;
    // Split the input text into individual words
    var words = inputText.split(" ");
    // Initialize an empty output string
    var outputText = "";
    // Loop through each word in the input text
    for (var i = 0; i < words.length; i++) {
        var word = words[i];
        // Check if the word exists in the dictionary
        if (word in dictionary) {
            // Add the translated word to the output string
            outputText += dictionary[word] + " ";
        } else {
            // If the word doesn't exist, use the original word
            outputText += word + " ";
        }
    }
    // Set the output text in the HTML element
    document.getElementById("nova").value = outputText;
}

// Function to translate Nova to English
function translateNovaToEnglish() {
    // Get the input text from the HTML element
    var inputText = document.getElementById("nova2").value;
    // Split the input text into individual words
    var words = inputText.split(" ");
    // Initialize an empty output string
    var outputText = "";
    // Loop through each word in the input text
    for (var i = 0; i < words.length; i++) {
        var word = words[i];
        // Check if the word exists in the dictionary
        if (Object.values(dictionary).indexOf(word) !== -1) {
            // Add the translated word to the output string
            outputText += Object.keys(dictionary)[Object.values(dictionary).indexOf(word)] + " ";
        } else {
            // If the word doesn't exist, use the original word
            outputText += word + " ";
        }
    }
    // Set the output text in the HTML element
    document.getElementById("english2").value = outputText;
}
